# Generated by Django 5.2 on 2025-04-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите аватар",
                null=True,
                upload_to="user_avatar/",
                verbose_name="Аватар:",
            ),
        ),
    ]
