# Generated by Django 5.2 on 2025-04-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_appuser_avatar"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="appuser",
            managers=[],
        ),
    ]
