# Generated by Django 5.2 on 2025-05-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_appuser_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appuser",
            options={
                "ordering": ["email"],
                "permissions": [
                    ("can_see_list_user", "Может видеть список пользователей сервиса")
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
