# Generated by Django 5.2 on 2025-05-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_appuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appuser",
            options={
                "ordering": ["email"],
                "permissions": [
                    ("can_see_list_user", "Может видеть список пользователей сервиса"),
                    ("can_block_user", "Может блокировать пользователей сервиса"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="appuser",
            name="is_blocked",
            field=models.BooleanField(
                default=False,
                help_text="Укажите заблокирован или нет пользователь",
                verbose_name="Статус блокировки пользователя:",
            ),
        ),
    ]
