# Generated by Django 5.2 on 2025-04-10 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailingRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Укажите почту получателя",
                        max_length=254,
                        unique=True,
                        verbose_name="Почта получателя:",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="Укажите Ф.И.О. получателя",
                        max_length=200,
                        null=True,
                        verbose_name="Ф.И.О. получателя:",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Укажите комментарий о получателе",
                        null=True,
                        verbose_name="Комментарий:",
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "db_table": "mailing_recipient",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_subject",
                    models.CharField(
                        help_text="Введите тему письма",
                        max_length=250,
                        verbose_name="Тема письма:",
                    ),
                ),
                (
                    "message_body",
                    models.TextField(
                        help_text="Введите суть письма", verbose_name="Тело письма:"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "db_table": "message",
                "ordering": ["message_subject"],
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_message_sending",
                    models.DateTimeField(
                        blank=True,
                        help_text="Укажите дату и время первой отправки",
                        null=True,
                        verbose_name="Дата и время первой отправки:",
                    ),
                ),
                (
                    "end_message_sending",
                    models.DateTimeField(
                        blank=True,
                        help_text="Укажите дату и время окончания отправки",
                        null=True,
                        verbose_name="Дата и время окончания отправки:",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("launched", "Запущена"),
                            ("accomplished", "Завершена"),
                        ],
                        default="created",
                        help_text="Укажите статус рассылки",
                        max_length=50,
                        verbose_name="Статус рассылки:",
                    ),
                ),
                (
                    "mailing_recipients",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Укажите получателей для рассылки",
                        related_name="mailings",
                        to="app_mailing.mailingrecipient",
                        verbose_name="Получатели для рассылки:",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="Укажите сообщение для рассылки",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailings",
                        to="app_mailing.message",
                        verbose_name="Сообщение для рассылки:",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "db_table": "mailing",
                "ordering": ["message"],
            },
        ),
    ]
