# Generated by Django 5.2 on 2025-04-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="mailing",
            table="tb_mailing",
        ),
        migrations.AlterModelTable(
            name="mailingrecipient",
            table="tb_mailing_recipient",
        ),
        migrations.AlterModelTable(
            name="message",
            table="tb_message",
        ),
    ]
