# Generated by Django 5.2 on 2025-04-10 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_mailing",
            "0002_alter_mailing_table_alter_mailingrecipient_table_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MailingRecipient",
            new_name="Recipient",
        ),
        migrations.RenameField(
            model_name="mailing",
            old_name="mailing_recipients",
            new_name="recipients",
        ),
        migrations.AlterModelTable(
            name="recipient",
            table="tb_recipient",
        ),
    ]
