# Generated by Django 5.2 on 2025-04-22 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_mailing", "0003_rename_mailingrecipient_recipient_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Укажите дату и время попытки рассылки",
                        verbose_name="Дата и время попытки рассылки:",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failed", "Не успешно")],
                        help_text="Укажите статус попытки рассылки",
                        max_length=15,
                        verbose_name="Статус попытки рассылки:",
                    ),
                ),
                (
                    "server_response",
                    models.TextField(
                        blank=True,
                        help_text="Укажите ответ почтового сервера",
                        null=True,
                        verbose_name="Ответ почтового сервера:",
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        help_text="Укажите рассылку",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="app_mailing.mailing",
                        verbose_name="Рассылка:",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="Укажите получателя, которому была отправлена рассылка",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="app_mailing.recipient",
                        verbose_name="Получатель:",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
                "db_table": "tb_attempt",
                "ordering": ["-attempt_time"],
            },
        ),
    ]
