# Generated by Django 5.2 on 2025-05-15 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_mailing", "0005_recipient_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Пользователь, которому принадлежит эта попытка",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель попытки рассылки:",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Пользователь, запустивший эту рассылку",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель рассылки:",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Пользователь, создавший это сообщение для рассылки",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель сообщения для рассылки:",
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Пользователь, создавший этого получателя рассылки",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель получателя рассылки:",
            ),
        ),
    ]
