# Generated by Django 5.2 on 2025-05-15 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_mailing", "0006_attempt_owner_mailing_owner_message_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="email",
            field=models.EmailField(
                help_text="Укажите почту получателя",
                max_length=254,
                verbose_name="Почта получателя:",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipient",
            constraint=models.UniqueConstraint(
                fields=("owner", "email"), name="unique_recipient_per_owner"
            ),
        ),
    ]
